name: Spleef-OG
main: org.battleplugins.arena.spleef.ArenaSpleef
version: ${version}
description: A Spleef mode for BattleArena.
author: BattlePlugins
website: https://battleplugins.org
api-version: ${apiVersion}
depend: [BattleArena, WorldGuard]
softdepend: [WorldEdit]
