name: Spleef-OG
main: net.trueog.spleefog.SpleefPlugin
version: ${version}
description: Classic and Bow Spleef in WorldGuard regions.
author: TrueOG
website: https://github.com/true-og/Spleef-OG
api-version: ${apiVersion}
depend: [WorldGuard]
softdepend: [MyWorlds, GameModeInventories-OG, PlayerBounties-OG]
commands:
  spleef:
    description: Join, spectate, and manage Spleef arenas.
    usage: /spleef
permissions:
  spleef.play:
    default: true
  spleef.spectate:
    default: true
  spleef.stats:
    default: true
  spleef.admin:
    default: op
